// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD91zsVLmJEfiKTKlvdeZvF3r9j24YQJpU',
    appId: '1:374428838042:web:a430b8b6f2e2020a4f9723',
    messagingSenderId: '374428838042',
    projectId: 'taknak-prod',
    authDomain: 'taknak-prod.firebaseapp.com',
    storageBucket: 'taknak-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAEmtZo97EzXsh0lOTOhDexvNw3mfQ-G4',
    appId: '1:374428838042:android:0bf65d275cfd6a564f9723',
    messagingSenderId: '374428838042',
    projectId: 'taknak-prod',
    storageBucket: 'taknak-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA46J5gfQGceNmAWV0doBOJml0mhxYRj08',
    appId: '1:374428838042:ios:4f54797317deba334f9723',
    messagingSenderId: '374428838042',
    projectId: 'taknak-prod',
    storageBucket: 'taknak-prod.firebasestorage.app',
    iosBundleId: 'com.example.ilkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA46J5gfQGceNmAWV0doBOJml0mhxYRj08',
    appId: '1:374428838042:ios:4f54797317deba334f9723',
    messagingSenderId: '374428838042',
    projectId: 'taknak-prod',
    storageBucket: 'taknak-prod.firebasestorage.app',
    iosBundleId: 'com.example.ilkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD91zsVLmJEfiKTKlvdeZvF3r9j24YQJpU',
    appId: '1:374428838042:web:f3830c9369b7c7634f9723',
    messagingSenderId: '374428838042',
    projectId: 'taknak-prod',
    authDomain: 'taknak-prod.firebaseapp.com',
    storageBucket: 'taknak-prod.firebasestorage.app',
  );
}